name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
     

jobs:
  build-liblzma:
    strategy:
      matrix:
        platform: [linux-x64, windows-x64, windows-x86, macos-arm64, macos-x64]
        include:
          - platform: linux-x64
            os: ubuntu-latest
            triplet: x64-linux

          - platform: windows-x64
            os: windows-latest
            triplet: x64-windows

          - platform: windows-x86
            os: windows-latest
            triplet: x86-windows

          - platform: macos-arm64
            os: macos-latest
            triplet: arm64-osx

          - platform: macos-x64
            os: macos-latest
            triplet: x64-osx

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11 # microsoft/vcpkg-action@v2
        with:
          vcpkgGitCommitId: "81e3c888ef717a026eb57bb2f3cb0dbd30246271"

      - name: Install liblzma
        shell: bash
        run: |
          vcpkg install liblzma:${{ matrix.triplet }} #--no-binarycaching
      
      - name: Copy liblzma to Output Directory
        shell: bash
        run: |
            find vcpkg/installed/${{ matrix.triplet }}
      #     mkdir -p ZCS.XZ/target/release/${{ matrix.triplet }}
      #     #cp hypertrie/target/${{ matrix.target }}/release/${{ matrix.lib_name }} ZCS.XZ/target/release/${{ matrix.output_dir }}/
      
      # - name: Upload Library
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: native-lib-${{ matrix.platform }}
      #     path: ZCS.XZ/target/release/${{ matrix.output_dir }}

  # build-nuget:
  #   needs: [build-liblzma]
  #   runs-on: ubuntu-latest
  #   if: always() && needs.build-liblzma.result == 'success'
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Install .NET SDK
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '10.0.x'
      
  #     - name: Download Linux Library
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: native-lib-linux-x64
  #         path: ZCS.XZ/target/release/linux-x64
      
  #     - name: Download Windows x64 Library
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: native-lib-windows-x64
  #         path: ZCS.XZ/target/release/windows-x64
      
  #     - name: Download Windows x86 Library
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: native-lib-windows-x86
  #         path: ZCS.XZ/target/release/windows-x86
      
  #     - name: Download macOS ARM64 Library
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: native-lib-macos-arm64
  #         path: ZCS.XZ/target/release/osx-arm64
      
      