name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-liblzma:
    strategy:
      fail-fast: false
      #max-parallel: 1
      matrix: &platforms_matrix
        platform: [linux-x64, linux-arm64, windows-x64, windows-arm64, macos-x64, macos-arm64]
        include:
          - platform: linux-x64
            os: ubuntu-latest
            triplet: x64-linux-dynamic
            lib_file: lib/liblzma.so
            exe_file: tools/liblzma/xz
            runtime_arch: linux-x64

          - platform: linux-arm64
            os: ubuntu-24.04-arm
            triplet: arm64-linux-dynamic
            lib_file: lib/liblzma.so
            exe_file: tools/liblzma/xz
            runtime_arch: linux-arm64

          - platform: windows-x64
            os: windows-latest
            triplet: x64-windows
            lib_file: bin/liblzma.dll
            exe_file: tools/liblzma/xz.exe
            runtime_arch: win-x64

          - platform: windows-arm64
            os: windows-11-arm
            triplet: arm64-windows
            lib_file: bin/liblzma.dll
            exe_file: tools/liblzma/xz.exe
            runtime_arch: win-arm64

          - platform: macos-x64
            os: macos-latest
            triplet: x64-osx-dynamic
            lib_file: lib/liblzma.dylib
            exe_file: tools/liblzma/xz
            runtime_arch: osx-x64

          - platform: macos-arm64
            os: macos-latest
            triplet: arm64-osx-dynamic
            lib_file: lib/liblzma.dylib
            exe_file: tools/liblzma/xz
            runtime_arch: osx-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "81e3c888ef717a026eb57bb2f3cb0dbd30246271"

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Build liblzma
        shell: bash
        run: |
          vcpkg install liblzma:${{ matrix.triplet }}

      - name: Copy to runtimes
        shell: bash
        run: |
          mkdir -p ZCS.XZ/runtimes/${{ matrix.runtime_arch }}/native
          cp -L vcpkg/installed/${{ matrix.triplet }}/${{ matrix.lib_file }} ZCS.XZ/runtimes/${{ matrix.runtime_arch }}/native/

      - name: Check if xz installed (needed only for testing)
        shell: bash
        run: |
          xz --version

      - name: Build and test
        shell: bash
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
          dotnet test -c Release --no-build 

      - name: Upload native library artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-lib-${{ matrix.platform }}
          path: ZCS.XZ/runtimes

  build-nupkg:
    needs: [build-liblzma]
    runs-on: ubuntu-latest
    if: always() && needs.build-liblzma.result == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Download all native library artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: native-lib-*
          path: ZCS.XZ/runtimes
          merge-multiple: true

      - name: Pack NuGet package
        run: dotnet pack ZCS.XZ/ZCS.XZ.csproj -c Release -o nupkgs

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: nupkgs/*.nupkg

  validate-nupkg:
    needs: [build-nupkg]
    if: always() && needs.build-nupkg.result == 'success'
    strategy:
      fail-fast: false
      #max-parallel: 1
      matrix: *platforms_matrix

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Download NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          pattern: nuget-package
          path: nupkgs

      - name: Validate NuGet package
        shell: bash
        run: |
          # We run the ValidateNupkg project, which references the built package,
          # to ensure that it can be used correctly, before we push it to nuget.org.
          cd ValidateNupkg
          dotnet restore
          dotnet build -c Release --no-restore
          dotnet run -c Release --no-build -f net8.0
          dotnet run -c Release --no-build -f net9.0
          dotnet run -c Release --no-build -f net10.0

  publish-nupkg:
    needs: [validate-nupkg]
    runs-on: ubuntu-latest
    if: always() && needs.validate-nupkg.result == 'success' && github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4

      - name: Download NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          pattern: nuget-package
          path: nupkgs

      # Publish to NuGet.org only on release events
      - name: Publish to NuGet.org
        if: github.event_name == 'release'
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate